import { describe, expect, it, vi } from 'vitest';

import {
  AtlasReleaseError,
  compareAtlasVersions,
  fetchLatestAtlasRelease,
  parseSha256File,
  versionFromReleaseTag,
} from './github-release';

const SHA256 = 'a'.repeat(64);
const APK_URL =
  'https://github.com/jesus-molano/atlas-habits/releases/download/v0.2.0/atlas.apk';
const CHECKSUM_URL = `${APK_URL}.sha256`;

describe('GitHub Release updater', () => {
  it('reads the two exact release assets and their checksum', async () => {
    const fetchImpl = vi
      .fn<typeof fetch>()
      .mockResolvedValueOnce(
        Response.json({
          assets: [
            {
              browser_download_url: APK_URL,
              name: 'atlas.apk',
              size: 42_000_000,
            },
            {
              browser_download_url: CHECKSUM_URL,
              name: 'atlas.apk.sha256',
              size: 76,
            },
          ],
          body: 'Cambios de prueba',
          draft: false,
          html_url:
            'https://github.com/jesus-molano/atlas-habits/releases/tag/v0.2.0',
          id: 123,
          name: 'Atlas 0.2.0',
          prerelease: false,
          published_at: '2026-08-31T12:00:00Z',
          tag_name: 'v0.2.0',
        }),
      )
      .mockResolvedValueOnce(
        new Response(`${SHA256}  atlas.apk\n`, { status: 200 }),
      );

    const release = await fetchLatestAtlasRelease({ fetchImpl });

    expect(release).toMatchObject({
      apkUrl: APK_URL,
      checksumUrl: CHECKSUM_URL,
      sha256: SHA256,
      version: '0.2.0',
    });
    expect(fetchImpl).toHaveBeenCalledTimes(2);
  });

  it('rejects release assets outside the official repository', async () => {
    const fetchImpl = vi.fn<typeof fetch>().mockResolvedValueOnce(
      Response.json({
        assets: [
          {
            browser_download_url:
              'https://github.com/attacker/atlas-habits/releases/download/v9.0.0/atlas.apk',
            name: 'atlas.apk',
            size: 1,
          },
          {
            browser_download_url: CHECKSUM_URL,
            name: 'atlas.apk.sha256',
            size: 76,
          },
        ],
        body: null,
        draft: false,
        html_url:
          'https://github.com/jesus-molano/atlas-habits/releases/tag/v9.0.0',
        id: 124,
        name: null,
        prerelease: false,
        published_at: null,
        tag_name: 'v9.0.0',
      }),
    );

    await expect(fetchLatestAtlasRelease({ fetchImpl })).rejects.toMatchObject({
      code: 'invalid_release',
    });
  });
});

describe('checksum parser', () => {
  it('accepts the sha256sum format generated by the release workflow', () => {
    expect(parseSha256File(`${SHA256.toUpperCase()}  atlas.apk\n`)).toBe(
      SHA256,
    );
  });

  it('rejects duplicate or unrelated checksum entries', () => {
    expect(() => parseSha256File(`${SHA256}  other.apk\n`)).toThrow(
      AtlasReleaseError,
    );
    expect(() =>
      parseSha256File(`${SHA256}  atlas.apk\n${SHA256}  atlas.apk\n`),
    ).toThrow(AtlasReleaseError);
  });
});

describe('version comparison', () => {
  it('normalizes release tags and compares stable versions', () => {
    expect(versionFromReleaseTag('v1.2.3')).toBe('1.2.3');
    expect(compareAtlasVersions('1.3.0', '1.2.9')).toBe(1);
    expect(compareAtlasVersions('1.2.3', '1.2.3')).toBe(0);
    expect(compareAtlasVersions('1.2.2', '1.2.3')).toBe(-1);
  });

  it('orders prerelease identifiers according to semantic-version precedence', () => {
    expect(compareAtlasVersions('1.0.0', '1.0.0-rc.1')).toBe(1);
    expect(compareAtlasVersions('1.0.0-rc.2', '1.0.0-rc.1')).toBe(1);
    expect(compareAtlasVersions('1.0.0-beta.2', '1.0.0-beta.11')).toBe(-1);
  });
});
